import {
  House,
  SquaresFour,
  FilmStrip,
  BookOpen,
  UsersThree,
  RoadHorizon,
  CaretDown,
  CaretRight,
  CaretLeft,
  ArrowUpRight,
  ArrowRight,
  UploadSimple,
  DownloadSimple,
  MagnifyingGlass,
  SlidersHorizontal,
  X,
  Play,
  Pause,
  VideoCamera,
  Clock,
  Car,
  ShieldCheck,
  Warning,
  CheckCircle,
  Info,
  GithubLogo,
  ArrowsOutSimple,
  ArrowsInSimple,
  ArrowCounterClockwise,
  FileJs,
  Eye,
  List,
  Sun,
  CloudSun,
  Moon,
  ChartBar,
  ChartLineUp,
  Check,
  TrafficSignal,
  PersonSimpleWalk,
  ArrowUUpLeft,
  DotsThree,
  ArrowSquareOut,
  Crosshair,
  Stack,
  Cpu,
} from "@phosphor-icons/react";
import type { IconProps } from "@phosphor-icons/react";

const icons = {
  home: House,
  grid: SquaresFour,
  film: FilmStrip,
  book: BookOpen,
  team: UsersThree,
  road: RoadHorizon,
  down: CaretDown,
  right: CaretRight,
  left: CaretLeft,
  external: ArrowUpRight,
  arrow: ArrowRight,
  upload: UploadSimple,
  download: DownloadSimple,
  search: MagnifyingGlass,
  filter: SlidersHorizontal,
  close: X,
  play: Play,
  pause: Pause,
  camera: VideoCamera,
  clock: Clock,
  car: Car,
  shield: ShieldCheck,
  warning: Warning,
  circleCheck: CheckCircle,
  info: Info,
  github: GithubLogo,
  expand: ArrowsOutSimple,
  collapse: ArrowsInSimple,
  reset: ArrowCounterClockwise,
  json: FileJs,
  eye: Eye,
  menu: List,
  sun: Sun,
  cloud: CloudSun,
  moon: Moon,
  bars: ChartBar,
  chart: ChartLineUp,
  check: Check,
  signal: TrafficSignal,
  person: PersonSimpleWalk,
  turn: ArrowUUpLeft,
  more: DotsThree,
  open: ArrowSquareOut,
  target: Crosshair,
  stack: Stack,
  cpu: Cpu,
};

export type IconName = keyof typeof icons;
export function Icon({
  name,
  size = 20,
  ...props
}: IconProps & { name: IconName }) {
  const Component = icons[name];
  return (
    <Component size={size} weight="regular" aria-hidden="true" {...props} />
  );
}
